# -*- coding: utf-8 -*-
"""Streamlit_run.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ArqKGC80TY3PgS2UyYOXgHGmnJNTE3-t
"""

!pip install -q diffusers==0.30.2 transformers==4.44.2 huggingface_hub==0.25.2 controlnet-aux==0.0.7 accelerate sentencepiece timm streamlit==1.37 pyngrok
!pip install -q torchvision opencv-python-headless

from diffusers import ControlNetModel, StableDiffusionControlNetPipeline

controlnet = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-canny")
pipe = StableDiffusionControlNetPipeline.from_pretrained(
	"runwayml/stable-diffusion-v1-5", controlnet=controlnet
)

from diffusers import ControlNetModel, StableDiffusionControlNetPipeline
from controlnet_aux import CannyDetector
import torch

dtype = torch.float16 if torch.cuda.is_available() else torch.float32

controlnet = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-canny", torch_dtype=dtype)
pipe = StableDiffusionControlNetPipeline.from_pretrained("SG161222/Realistic_Vision_V5.1_noVAE", controlnet=controlnet, torch_dtype=dtype)
pipe = pipe.to("cuda" if torch.cuda.is_available() else "cpu")

# save locally
controlnet.save_pretrained("/content/sd_controlnet_canny")
pipe.save_pretrained("/content/rv_v5.1_pipe")
print("Preload complete — saved to /content/")

# open ngrok
from pyngrok import ngrok
ngrok.set_auth_token("ngroktoken")    # get from ngrok dashboard
public_url = ngrok.connect(8501)
print("Public URL:", public_url)

# run streamlit
!streamlit run /content/app.py --server.port 8501 --server.headless true

import os
os.environ["HF_TOKEN"] = "Huggingfacetoken"